import type { ReportData } from "../types/report";

export const sampleReportData: ReportData = {
  id: "sample-household",
  householdName: "Sample Client Household",
  profile: {
    client1Name: "Sample Client",
    client1Dob: "1968-04-18",
    client1SsnLastFour: "1245",
    client2Name: "Sample Spouse",
    client2Dob: "1970-09-06",
    client2SsnLastFour: "7788",
    reportDate: "2026-03-31",
  },
  sacs: {
    monthlyInflow: 15000,
    monthlyOutflow: 12000,
    bufferFloor: 1000,
    privateReserveBalance: 30000,
    schwabBrokerageBalance: 80000,
    insuranceDeductibles: 5000,
    inflowAccount: {
      id: "inflow-main",
      label: "Primary Inflow",
      institutionName: "Payroll / Income Sweep",
      lastFour: "1001",
      currency: "USD",
      localBalance: 15000,
      usdValue: 15000,
    },
    outflowAccount: {
      id: "outflow-main",
      label: "Monthly Living Expenses",
      institutionName: "Household Checking",
      lastFour: "2200",
      currency: "USD",
      localBalance: 12000,
      usdValue: 12000,
    },
    privateReserveAccount: {
      id: "reserve-main",
      label: "Private Reserve",
      institutionName: "Private Reserve Savings",
      lastFour: "3300",
      currency: "USD",
      localBalance: 30000,
      usdValue: 30000,
    },
    budgetWorksheet: [
      { id: "mortgage", category: "Mortgage or Rent", monthlyAmount: 4200, amountToTransfer: 4200 },
      { id: "utilities", category: "Utilities", monthlyAmount: 850, amountToTransfer: 850 },
      { id: "insurance", category: "Insurance", monthlyAmount: 1250, amountToTransfer: 1250 },
      { id: "food", category: "Food at Home / Meals", monthlyAmount: 1800, amountToTransfer: 1800 },
      { id: "transport", category: "Auto / Gas / Maintenance", monthlyAmount: 1400, amountToTransfer: 1400 },
      { id: "health", category: "Health / Medical Out of Pocket", monthlyAmount: 900, amountToTransfer: 900 },
      { id: "other", category: "Other Monthly Expenses", monthlyAmount: 1600, amountToTransfer: 1600 },
    ],
  },
  client1RetirementAccounts: [
    {
      id: "c1-ira",
      accountType: "Traditional IRA",
      lastFour: "4182",
      balance: 465000,
      cashBalance: 18000,
      asOfDate: "2026-03-31",
    },
    {
      id: "c1-401k",
      accountType: "401(k)",
      lastFour: "9920",
      balance: 725000,
      cashBalance: 24500,
      asOfDate: "2026-03-31",
    },
  ],
  client2RetirementAccounts: [
    {
      id: "c2-ira",
      accountType: "Roth IRA",
      lastFour: "3307",
      balance: 298000,
      cashBalance: 9200,
      asOfDate: "2026-03-31",
    },
    {
      id: "c2-403b",
      accountType: "403(b)",
      lastFour: "6401",
      balance: 384000,
      cashBalance: 12750,
      asOfDate: "2026-03-31",
    },
  ],
  nonRetirementAccounts: [
    {
      id: "joint-taxable",
      accountType: "Joint Brokerage",
      institutionName: "Schwab",
      lastFour: "8502",
      balance: 512000,
      asOfDate: "2026-03-31",
    },
    {
      id: "cash-reserve",
      accountType: "High Yield Savings",
      institutionName: "Ally Bank",
      lastFour: "1180",
      balance: 94000,
      asOfDate: "2026-03-31",
    },
  ],
  trust: {
    trustName: "Sample Family Revocable Trust",
    propertyAddress: "2148 Willow Creek Drive, Boulder, CO",
    estimatedHomeValue: 925000,
    asOfDate: "2026-03-31",
  },
  liabilities: [
    {
      id: "mortgage",
      liabilityType: "Primary Mortgage",
      lenderName: "First National Bank",
      interestRate: 3.25,
      balance: 382500,
      asOfDate: "2026-03-31",
    },
    {
      id: "auto-loan",
      liabilityType: "Auto Loan",
      lenderName: "Credit Union",
      interestRate: 4.9,
      balance: 18500,
      asOfDate: "2026-03-31",
    },
  ],
};

export const sampleClients: ReportData[] = [
  sampleReportData,
  {
    ...sampleReportData,
    id: "patel-household",
    householdName: "Patel Household",
    profile: {
      ...sampleReportData.profile,
      client1Name: "Anika Patel",
      client1Dob: "1972-02-11",
      client1SsnLastFour: "4401",
      client2Name: "Rahul Patel",
      client2Dob: "1971-10-28",
      client2SsnLastFour: "1189",
    },
    sacs: {
      ...sampleReportData.sacs,
      monthlyInflow: 18500,
      monthlyOutflow: 13800,
      privateReserveBalance: 46000,
      inflowAccount: {
        ...sampleReportData.sacs.inflowAccount,
        usdValue: 18500,
        localBalance: 18500,
        lastFour: "7421",
      },
      outflowAccount: {
        ...sampleReportData.sacs.outflowAccount,
        usdValue: 13800,
        localBalance: 13800,
        lastFour: "9105",
      },
    },
  },
  {
    ...sampleReportData,
    id: "roberts-household",
    householdName: "Roberts Household",
    profile: {
      ...sampleReportData.profile,
      client1Name: "Morgan Roberts",
      client1Dob: "1965-06-04",
      client1SsnLastFour: "7053",
      client2Name: "Dana Roberts",
      client2Dob: "1967-12-14",
      client2SsnLastFour: "2290",
    },
    sacs: {
      ...sampleReportData.sacs,
      monthlyInflow: 11250,
      monthlyOutflow: 9200,
      privateReserveBalance: 28000,
      inflowAccount: {
        ...sampleReportData.sacs.inflowAccount,
        usdValue: 11250,
        localBalance: 11250,
        lastFour: "6120",
      },
      outflowAccount: {
        ...sampleReportData.sacs.outflowAccount,
        usdValue: 9200,
        localBalance: 9200,
        lastFour: "0048",
      },
    },
  },
];
